/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNIUsage_HelloJNI_testJNI */

#ifndef _Included_JNIUsage_HelloJNI_testJNI
#define _Included_JNIUsage_HelloJNI_testJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIUsage_HelloJNI_testJNI
 * Method:    sayHelloFromCPP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIUsage_HelloJNI_testJNI_sayHelloFromCPP
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
