/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIUsage_TypeJNI_testType */

#ifndef _Included_JNIUsage_TypeJNI_testType
#define _Included_JNIUsage_TypeJNI_testType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIUsage_TypeJNI_testType
 * Method:    getStringFromCPP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIUsage_TypeJNI_testType_getStringFromCPP
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
